name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build HTML
      run: echo "Build HTML steps go here"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: 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
        BRANCH: gh-pages
        FOLDER: .   # Change this if your HTML file is in a different folder
