name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Live Server
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the server's host key to known_hosts
        ssh-keyscan -p 22445 103.76.249.124 >> ~/.ssh/known_hosts

        rsync -av --delete -e "ssh -p 22445" \
          --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github \
          ./ root@103.76.249.124:/home/demoemal/public_html/cicd
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
